name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit & Database Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-mock

      - name: Run Unit Tests (Mocked DB)
        run: |
          pytest -v --disable-warnings

      - name: Run Database Tests
        env:
          DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/test_db
        run: |
          pytest -v --disable-warnings

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test  # Only runs if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t fastapi-app .
          docker tag fastapi-app ghcr.io/${{ github.repository }}/fastapi-app:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/fastapi-app:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image from GitHub Container Registry..."
            docker pull ghcr.io/${{ github.repository }}/fastapi-app:latest

            echo "Stopping and removing old container..."
            docker stop fastapi-container || true
            docker rm fastapi-container || true

            echo "Running new container..."
            docker run -d --name fastapi-container -p 8000:8000 --env-file .env ghcr.io/${{ github.repository }}/fastapi-app:latest

            echo "Deployment complete!"
